# Generated by Django 4.0.8 on 2022-12-29 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressbooks', '0003_alter_contact_options_alter_group_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
