# Generated by Django 4.0.8 on 2022-12-31 16:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('addressbooks', '0004_alter_group_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('user', 'name')},
        ),
    ]
